// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'home-container': string;
  'layout-slider-container': string;
  'logo-container': string;
  'logo-img': string;
  'logo-name': string;
  'slider-logo-container': string;
}
export const cssExports: CssExports;
export default cssExports;
