// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'home-container': string;
  'layout-header-container': string;
  'right-container': string;
  'trigger-container': string;
  'user-container': string;
}
export const cssExports: CssExports;
export default cssExports;
