// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'home-container': string;
  'icon-text-container': string;
  'text-container': string;
}
export const cssExports: CssExports;
export default cssExports;
