// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'home-container': string;
  'test': string;
}
export const cssExports: CssExports;
export default cssExports;
